### ISSUE TITLE
Add documentation on how to use the Docker images

### ISSUE THREAD

**Issue by PierreZ** [FoundationDB/fdb-build-support#10]
The issue is related to apple/foundationDB#5717. We should add some documentation on:

1. how-to use the `build` image:
    * to build FDB,
1. how-to use the `devel` image, to use:
    * vscode server,
    * joshua(I wonder if we should document this here or on the joshua repo, which also needs some documentation :thinking:),
1. how-to use the `distcc` image, to use:
    * distcc,
1. how-to use the `codebuild` image.

I would love to help on this(and also on Joshua's documentation), but I'm only familiar with the `build` image for now.

**Comment by ammolitor** [comment]
Updated the README.md with descriptions. Any further documentation should go in the [README.md in the main foundationdb repo](https://github.com/apple/foundationdb/blob/main/README.md)
