### ISSUE TITLE
Find next linux base os for build images

### ISSUE THREAD

**Issue by ammolitor** [FoundationDB/fdb-build-support#25]
With the CentOS project shifting course, and EOL'ing CentOS 8. We need to find an alternative distribution before CentOS 7 ages out of relevancy. 

Possible alternatives (not researched, and in no particular order) could be:
* Oracle Linux
* ALMA Linux
* RHEL
* Rocky Linux
* Fedora

**Comment by gm42** [comment]
FYI, Centos 7 reached EOL on 30th June: https://www.redhat.com/en/topics/linux/centos-linux-eol

This will start triggering security warnings.
